config/routes.rb
Rails.application.routes.draw do
  resources :turatsinzes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/personal.rb
class Personal < ApplicationRecord
end

app/models/turatsinze.rb
class Turatsinze < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/turatsinzes_controller.rb
class TuratsinzesController < ApplicationController
  before_action :set_turatsinze, only: [:show, :edit, :update, :destroy]

  # GET /turatsinzes
  # GET /turatsinzes.json
  def index
    @turatsinzes = Turatsinze.all
  end

  # GET /turatsinzes/1
  # GET /turatsinzes/1.json
  def show
  end

  # GET /turatsinzes/new
  def new
    @turatsinze = Turatsinze.new
  end

  # GET /turatsinzes/1/edit
  def edit
  end

  # POST /turatsinzes
  # POST /turatsinzes.json
  def create
    @turatsinze = Turatsinze.new(turatsinze_params)

    respond_to do |format|
      if @turatsinze.save
        format.html { redirect_to @turatsinze, notice: 'Turatsinze was successfully created.' }
        format.json { render :show, status: :created, location: @turatsinze }
      else
        format.html { render :new }
        format.json { render json: @turatsinze.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turatsinzes/1
  # PATCH/PUT /turatsinzes/1.json
  def update
    respond_to do |format|
      if @turatsinze.update(turatsinze_params)
        format.html { redirect_to @turatsinze, notice: 'Turatsinze was successfully updated.' }
        format.json { render :show, status: :ok, location: @turatsinze }
      else
        format.html { render :edit }
        format.json { render json: @turatsinze.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turatsinzes/1
  # DELETE /turatsinzes/1.json
  def destroy
    @turatsinze.destroy
    respond_to do |format|
      format.html { redirect_to turatsinzes_url, notice: 'Turatsinze was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turatsinze
      @turatsinze = Turatsinze.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turatsinze_params
      params.require(:turatsinze).permit(:firstname, :lastname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/turatsinzes_helper.rb
module TuratsinzesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pedex</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/turatsinzes/_form.html.erb
<%= form_with(model: turatsinze, local: true) do |form| %>
  <% if turatsinze.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turatsinze.errors.count, "error") %> prohibited this turatsinze from being saved:</h2>

      <ul>
      <% turatsinze.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/turatsinzes/edit.html.erb
<h1>Editing Turatsinze</h1>

<%= render 'form', turatsinze: @turatsinze %>

<%= link_to 'Show', @turatsinze %> |
<%= link_to 'Back', turatsinzes_path %>

app/views/turatsinzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turatsinzes</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turatsinzes.each do |turatsinze| %>
      <tr>
        <td><%= turatsinze.firstname %></td>
        <td><%= turatsinze.lastname %></td>
        <td><%= link_to 'Show', turatsinze %></td>
        <td><%= link_to 'Edit', edit_turatsinze_path(turatsinze) %></td>
        <td><%= link_to 'Destroy', turatsinze, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turatsinze', new_turatsinze_path %>

app/views/turatsinzes/new.html.erb
<h1>New Turatsinze</h1>

<%= render 'form', turatsinze: @turatsinze %>

<%= link_to 'Back', turatsinzes_path %>

app/views/turatsinzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @turatsinze.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @turatsinze.lastname %>
</p>

<%= link_to 'Edit', edit_turatsinze_path(@turatsinze) %> |
<%= link_to 'Back', turatsinzes_path %>